name: Build Go Bridge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        arch: [386, amd64, arm64]
        include:
          - os: linux
            ext: ""
          - os: windows
            ext: ".exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/telegram-api-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-api-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/telegram-api-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}